name: QuantBot CI & Packaging
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build-and-package:
    runs-on: windows-latest 
    env:
      GIT_REDIRECT_STDERR: 2>&1  # 重定向Git错误输出 
    steps:
    - name: Configure Git
      run: |
        git config --global core.protectNTFS  false
        git config --global core.longpaths  true 
        git config --global core.symlinks  false 
 
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          * 
          !configs/strategy_presets/
          configs/strategy_presets/
        fetch-depth: 1 
        lfs: false
 
    - name: Safe file copy
      run: |
        # 创建安全构建环境 
        mkdir "$env:RUNNER_TEMP\safe-build"
        robocopy . "$env:RUNNER_TEMP\safe-build" /E /XD configs\strategy_presets /XF *.yaml
        
        # 手动复制需要的配置文件 
        mkdir "$env:RUNNER_TEMP\safe-build\configs\strategy_presets"
        copy "configs\strategy_presets\*.yaml" "$env:RUNNER_TEMP\safe-build\configs\strategy_presets\"
        
        cd "$env:RUNNER_TEMP\safe-build"
 
    - name: Build and package
      run: |
        pip install -r requirements.txt  pyinstaller 
        pyinstaller --noconfirm --onefile `
          --add-data "configs/strategy_presets/*.yaml;configs/strategy_presets" `
          main.py 
 
    - uses: actions/upload-artifact@v4 
      with:
        name: QuantBot-Windows
        path: "$env:RUNNER_TEMP\safe-build\dist\main.exe" 