name: CI Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest 
    timeout-minutes: 30 
    
    steps:
    - uses: actions/checkout@v3
 
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          cmake \
          automake \
          libtool \
          pkg-config \
          gfortran 
 
    - name: Download and build TA-Lib (patched)
      run: |
        # 使用备用下载源 
        wget https://github.com/TA-Lib/ta-lib/archive/refs/tags/v0.4.0.tar.gz  -O ta-lib-0.4.0.tar.gz  || 
          wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 
        
        tar -xzf ta-lib-*.tar.gz  
        cd ta-lib-*
        
        # 修复可能缺失的构建文件
        if [ ! -f configure ]; then
          autoreconf -fi
        fi 
        
        # 应用关键修复补丁
        sed -i.bak  's/MAKE="make -j\${MAKE_JOBS}"/MAKE="make"/' configure 
        sed -i.bak  's/make -j\${MAKE_JOBS}/make/' Makefile.* 
        
        ./configure \
          --prefix=/usr \
          --build=$(uname -m)-linux-gnu \
          --disable-static \
          --enable-shared \
          --disable-dependency-tracking
        
        make -j1
        sudo make install 
        sudo ldconfig
 
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install Python dependencies 
      run: |
        python -m pip install --upgrade pip wheel 
        pip install numpy==1.24.3
        pip install Cython==3.0.0
        TA_LIBRARY_PATH=/usr/lib TA_INCLUDE_PATH=/usr/include \
          pip install TA-Lib==0.4.24 \
          --global-option=build_ext \
          --global-option="-L/usr/lib" \
          --global-option="-I/usr/include" \
          --no-cache-dir \
          --no-build-isolation
 
    - name: Verify installation 
      run: |
        python -c "import talib; print('TA-Lib functions:', len(talib.get_functions()))" 
        python -c "import talib; print('TA-Lib version:', talib.__version__)"