name: Windows Production Build 
 
on: [push]
 
jobs:
  build:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v4 
 
    - name: Install dependencies 
      run: |
        choco install -y ta-lib 
        pip install numpy TA-Lib pyinstaller 
 
    - name: Build executable 
      run: |
        pyinstaller --onefile `
          --add-data "configs/strategy_presets;configs/strategy_presets" `
          --noconfirm `
          --clean `
          main.py  
 
    - uses: actions/upload-artifact@v4 
      with:
        name: QuantBot-Windows 
        path: dist/main.exe  