name: QuantBot Bulletproof Build
 
on: [push]
 
jobs:
  package:
    runs-on: windows-latest 
    steps:
    - name: 跳过问题目录检出 
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          * 
          !configs/strategy_presets/
        fetch-depth: 0  # 关键修改 
 
    - name: 手动创建配置目录
      run: |
        mkdir -p configs/strategy_presets
        # 从Git历史中单独提取配置文件 
        git show origin/main:configs/strategy_presets/rsi_macd.yaml  > configs/strategy_presets/rsi_macd.yaml 
        git show origin/main:configs/strategy_presets/custom_strategy.yaml  > configs/strategy_presets/custom_strategy.yaml 
 
    - name: 安装依赖
      run: |
        choco install -y ta-lib
        pip install numpy TA-Lib pyinstaller 
 
    - name: 构建可执行文件 
      run: |
        pyinstaller --onefile `
          --add-data "configs/strategy_presets;configs/strategy_presets" `
          --noconfirm `
          --clean `
          main.py  
 
    - uses: actions/upload-artifact@v4
      with:
        name: QuantBot-Windows 
        path: dist/main.exe 