name: TA-Lib Build Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build-ta-lib:
    runs-on: ubuntu-latest
    timeout-minutes: 30
 
    steps:
    - name: Install build dependencies 
      run: |
        sudo apt-get update 
        sudo apt-get install -y \
          build-essential \
          wget \
          automake \
          libtool \
          pkg-config 
 
    - name: Build and install TA-Lib 
      run: |
        # 下载源码（使用官方GitHub仓库）
        wget -O ta-lib.tar.gz  https://github.com/TA-Lib/ta-lib/archive/refs/tags/v0.4.0.tar.gz  
        mkdir -p ta-lib-src
        tar -xzf ta-lib.tar.gz  -C ta-lib-src --strip-components=1 
        cd ta-lib-src 
 
        # 修复subdir-objects问题 
        sed -i 's/^AM_INIT_AUTOMAKE.*/AM_INIT_AUTOMAKE([subdir-objects foreign])/' configure.ac 
 
        # 生成构建系统 
        autoreconf -vif || {
          aclocal
          autoheader
          automake --add-missing --foreign
          autoconf 
        }
 
        # 配置编译选项
        ./configure \
          --prefix=/usr \
          --disable-static \
          --enable-shared \
          --disable-dependency-tracking 
 
        # 编译安装（忽略子目录警告）
        make -j$(nproc) 2>&1 | grep -v "subdir-objects is disabled"
        sudo make install
        sudo ldconfig 
 
    - name: Verify installation 
      run: |
        ls /usr/lib/libta_lib.so*  && ls /usr/include/ta-lib/
        python3 -c "import ctypes; ctypes.CDLL('libta_lib.so.0')" 