name: QuantBot CI Pipeline 
 
on: [push, pull_request]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
 
    # 关键步骤1：显式创建项目目录结构 
    - name: Setup project structure
      run: |
        echo "当前工作目录: $(pwd)"
        mkdir -p QuantBot/libs 
        echo "创建的目录结构:"
        find . -maxdepth 3 -type d | sort
 
    # 关键步骤2：使用绝对路径构建TA-Lib 
    - name: Build TA-Lib
      run: |
        TA_LIB_DIR="$GITHUB_WORKSPACE/QuantBot/libs/ta-lib"
        mkdir -p "$TA_LIB_DIR"
        cd "$TA_LIB_DIR"
        
        wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 
        tar -xzf ta-lib-0.4.0-src.tar.gz  --strip-components=1 
        ./configure --prefix="$TA_LIB_DIR/install"
        make -j$(nproc)
        make install
 
        # 验证编译结果
        ls "$TA_LIB_DIR/install/lib/libta_lib.so"  || exit 1 
 
    # 关键步骤3：正确设置Python环境 
    - name: Install Python dependencies 
      run: |
        cd "$GITHUB_WORKSPACE/QuantBot"
        
        # 设置全局环境变量 
        echo "TA_LIBRARY_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/lib" >> $GITHUB_ENV 
        echo "TA_INCLUDE_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/include" >> $GITHUB_ENV
        
        pip install numpy Cython 
        TA_LIBRARY_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/lib \
        TA_INCLUDE_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/include \
        pip install TA-Lib
        
        [ -f requirements.txt  ] && pip install -r requirements.txt  
 
    - name: Verify installation 
      run: |
        cd "$GITHUB_WORKSPACE/QuantBot"
        python -c "
        import os, talib 
        print(f'TA-Lib loaded from: {os.path.dirname(talib.__file__)}') 
        print('RSI test:', talib.RSI([1,2,3,4,5]))
        " 