name: QuantBot CI 
 
on: [push, pull_request] 
 
jobs:
  package:
    runs-on: windows-latest 
    steps:
    - uses: actions/checkout@v4 
 
    - name: 安装依赖 
      run: |
        choco install -y ta-lib 
        pip install numpy Cython TA-Lib pyinstaller
 
    - name: 直接打包（跳过所有复杂配置）
      run: |
        pyinstaller --onefile --noconfirm --clean --add-data "configs/strategy_presets;configs/strategy_presets" main.py 
 
    - name: 上传成品 
      uses: actions/upload-artifact@v4 
      with:
        name: QuantBot-Windows
        path: dist/main.exe  