name: QuantBot CI Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
 
jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: QuantBot  # 关键修复点 
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
 
    - name: Install TA-Lib dependencies 
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          python3-dev
 
    - name: Build TA-Lib 
      run: |
        mkdir -p libs/ta-lib 
        cd libs/ta-lib
        wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz  
        tar -xzf ta-lib-0.4.0-src.tar.gz  --strip-components=1 
        ./configure --prefix=$PWD/install
        make -j$(nproc)
        make install
 
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install numpy Cython 
        
        # 使用绝对路径设置环境变量 
        echo "TA_LIBRARY_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/lib" >> $GITHUB_ENV 
        echo "TA_INCLUDE_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/include" >> $GITHUB_ENV
        
        # 安装TA-Lib Python包装器
        TA_LIBRARY_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/lib \
        TA_INCLUDE_PATH=$GITHUB_WORKSPACE/QuantBot/libs/ta-lib/install/include \
        pip install TA-Lib 
        
        # 可选：安装requirements.txt 
        [ -f requirements.txt  ] && pip install -r requirements.txt  || echo "No requirements.txt  found"
 
    - name: Verify installation 
      run: |
        python -c "import talib; print('TA-Lib version:', talib.__version__)"
        python -c "import numpy; print('NumPy version:', numpy.__version__)"