name: QuantBot Production Build 
 
on: [push]
 
jobs:
  package:
    runs-on: windows-latest 
    steps:
    - name: 强制重命名问题目录
      run: |
        # 临时重命名问题目录
        git clone https://github.com/FlynnQChen/QuantBot-.git  repo-temp
        cd repo-temp
        ren "configs\strategy_presets" strategy_configs 
        cd ..
        move repo-temp\* .
        rmdir /s /q repo-temp
 
    - name: 安装依赖
      run: |
        choco install -y ta-lib
        pip install numpy TA-Lib pyinstaller
 
    - name: 暴力打包
      run: |
        pyinstaller --onefile ^ 
          --add-data "configs/strategy_configs;configs/strategy_configs" ^
          --noconfirm ^ 
          --clean ^
          main.py 
 
    - uses: actions/upload-artifact@v4 
      with:
        name: QuantBot-Executable 
        path: dist/main.exe 