name: Windows Production Build
 
on: push 
 
jobs:
  package:
    runs-on: windows-latest 
    steps:
    - name: 下载源码压缩包
      run: |
        $headers = @{ Authorization = "token ${{ secrets.GITHUB_TOKEN }}" }
        Invoke-WebRequest -Uri "https://api.github.com/repos/FlynnQChen/QuantBot-/zipball/main"  -Headers $headers -OutFile repo.zip  
        Expand-Archive -Path repo.zip  -DestinationPath .
 
    - name: 准备构建环境 
      run: |
        # 获取解压后的随机目录名 
        $dir = Get-ChildItem | Where-Object { $_.Name -match 'FlynnQChen-QuantBot--' } | Select-Object -First 1 
        Move-Item -Path "$($dir.FullName)\*" -Destination . 
        Remove-Item repo.zip,  $dir -Recurse -Force 
 
    - name: 安装依赖 
      run: |
        choco install -y ta-lib 
        pip install numpy TA-Lib pyinstaller
 
    - name: 构建可执行文件
      run: |
        pyinstaller --onefile `
          --add-data "configs/strategy_presets/*.yaml;configs/strategy_presets" `
          --noconfirm --clean `
          main.py 
 
    - uses: actions/upload-artifact@v4 
      with:
        name: QuantBot-Windows
        path: dist/main.exe  