name: CI Pipeline 
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3
 
    - name: Set up Python 3.11 (recommended for TA-Lib)
      uses: actions/setup-python@v4 
      with:
        python-version: '3.11'
 
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          cmake \
          automake \
          libtool \
          pkg-config \
          gfortran 
 
    - name: Build TA-Lib C library
      run: |
        wget -O ta-lib.tar.gz  https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 
        tar -xzf ta-lib.tar.gz  
        cd ta-lib/
        ./configure --prefix=/usr 
        make -j$(nproc)
        sudo make install 
        sudo ldconfig
 
    - name: Install Python dependencies (with compatibility fixes)
      run: |
        # 安装兼容版本的构建工具
        python -m pip install --upgrade "pip<23.3" "setuptools<66.0.0" wheel
        
        # 安装必要依赖
        pip install numpy==1.24.3 Cython==3.0.0
        
        # 安装TA-Lib
        TA_LIBRARY_PATH=/usr/lib \ 
        TA_INCLUDE_PATH=/usr/include \
        pip install TA-Lib==0.4.24 \
          --global-option=build_ext \
          --global-option="-L/usr/lib" \
          --global-option="-I/usr/include" \
          --no-cache-dir \
          --no-build-isolation 
 
    - name: Verify installation
      run: |
        python -c "import talib; print('TA-Lib version:', talib.__version__)"
        python -c "from talib import RSI, MACD; print('Indicators working')"