name: CI Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest 
    timeout-minutes: 30 
    
    steps:
    - uses: actions/checkout@v3
 
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          automake \
          libtool \
          pkg-config 
 
    - name: Build TA-Lib with full autotools 
      run: |
        # 下载源码（使用GitHub官方镜像）
        wget -O ta-lib.tar.gz  https://github.com/TA-Lib/ta-lib/archive/refs/tags/v0.4.0.tar.gz 
        tar -xzf ta-lib.tar.gz  
        cd ta-lib-*
        
        # 关键修复：完整生成构建系统
        aclocal 
        autoheader 
        automake --add-missing --foreign 
        autoconf
        
        # 启用subdir-objects 
        sed -i 's/AM_INIT_AUTOMAKE.*/AM_INIT_AUTOMAKE([subdir-objects foreign])/' configure.ac  
        
        # 重新生成构建系统
        autoreconf -vif 
        
        # 配置编译选项 
        ./configure \ 
          --prefix=/usr \
          --disable-static \
          --enable-shared
        
        # 编译安装
        make -j$(nproc)
        sudo make install 
        sudo ldconfig
 
    - name: Verify installation 
      run: |
        ls /usr/lib/libta_lib.so*  && ls /usr/include/ta-lib/