name: QuantBot CI & Packaging
 
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      GIT_WILDCARD_PATHSPECS: 0  # 关键修复：禁用通配符路径规范 
    steps:
    - name: Configure Git 
      run: |
        git config --global core.protectNTFS  false
        git config --global core.longpaths  true
 
    - uses: actions/checkout@v4
      with: 
        sparse-checkout: |  # 明确指定要检出的路径 
          /*
          !configs/strategy_presets/
          configs/strategy_presets/*.yaml
 
    - name: Install TA-Lib
      run: |
        choco install -y ta-lib --version=0.4.0.1
        echo "TA_LIBRARY_PATH=C:\Program Files\ta-lib\lib" >> $env:GITHUB_ENV 
        echo "TA_INCLUDE_PATH=C:\Program Files\ta-lib\include" >> $env:GITHUB_ENV
 
    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
 
    - name: Build application 
      run: |
        # 创建安全路径的临时目录 
        $tempDir = New-Item -ItemType Directory -Path "$env:RUNNER_TEMP\build" -Force 
        Copy-Item -Path ".\*" -Destination $tempDir -Recurse -Exclude "configs\strategy_presets\unneeded_*"
        Set-Location $tempDir
        
        # 安装依赖
        pip install -r requirements.txt  pyinstaller 
        pip install numpy Cython TA-Lib
 
        # 打包 
        pyinstaller --noconfirm --onefile --windowed --add-data "configs/strategy_presets/*.yaml;configs/strategy_presets" main.py  
 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuantBot-Windows 
        path: dist/main.exe 
        retention-days: 3
        