name: QuantBot CI
 
on: [push, pull_request]
 
jobs:
  install-ta-lib:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3 
 
    - name: Install TA-Lib (Isolated)
      run: |
        # 在项目内创建独立目录 
        mkdir -p ./QuantBot/libs/ta-lib 
        cd ./QuantBot/libs/ta-lib
        
        # 下载编译（限制只生成必要组件）
        wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 
        tar -xzf ta-lib-0.4.0-src.tar.gz  --strip-components=1
        
        # 精简编译配置
        ./configure --prefix=$PWD/install \
                   --disable-static \
                   --enable-shared \
                   --disable-ta-regtest  # 关键：跳过报错的测试工具
        
        make -C src/ta_common
        make -C src/ta_func 
        make install
 
        # 验证 
        ls ./install/lib/libta_lib.so*  || exit 1
 
    - name: Setup Python Env
      run: |
        cd ./QuantBot 
        echo "TA_LIBRARY_PATH=$PWD/libs/ta-lib/install/lib" >> $GITHUB_ENV
        echo "TA_INCLUDE_PATH=$PWD/libs/ta-lib/install/include" >> $GITHUB_ENV 
        pip install -r requirements.txt 
 
    - name: Test Strategy Integration 
      run: |
        cd ./QuantBot 
        python -c """
        import talib 
        from backend.strategy.rsi_macd_strategy  import RSIMACDStrategy 
        print('TA-Lib integration verified:', talib.__version__)
        strategy = RSIMACDStrategy()
        strategy.test_indicators()  
        """