name: Windows Executable Build 
 
on: [push]
 
jobs:
  build:
    runs-on: windows-latest 
    steps:
    # 1. 直接下载代码（绕过Git检出问题）
    - name: Download Repository
      run: | 
        $repoUrl = "https://codeload.github.com/FlynnQChen/QuantBot-/zip/refs/heads/main" 
        $tempFile = "$env:TEMP\repo.zip" 
        Invoke-WebRequest -Uri $repoUrl -OutFile $tempFile 
        Expand-Archive -Path $tempFile -DestinationPath .
        Rename-Item -Path QuantBot--main -NewName source 
 
    # 2. 准备构建环境
    - name: Prepare Build Directory
      run: |
        mkdir build 
        copy source\* build -Recurse -Force 
 
    # 3. 安装必要组件
    - name: Install Requirements 
      run: |
        choco install -y ta-lib 
        pip install numpy TA-Lib pyinstaller
 
    # 4. 构建可执行文件 
    - name: Build Executable 
      working-directory: ./build 
      run: |
        pyinstaller --onefile `
          --add-data "configs/strategy_presets/*.yaml;configs/strategy_presets" `
          --noconfirm `
          --clean `
          main.py 
 
    # 5. 上传成品 
    - uses: actions/upload-artifact@v4
      with:
        name: QuantBot-Windows 
        path: build/dist/main.exe  