name: CI Pipeline 
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Validate requirements format 
      run: |
        # 检查空行和格式错误
        if grep -q "^[[:space:]]*$" requirements.txt;  then 
          echo "发现空行，请删除requirements.txt 中的空行"
          exit 1
        fi
        if ! grep -q "^[a-zA-Z]" requirements.txt;  then
          echo "requirements.txt 必须以包名开头"
          exit 1
        fi 
 
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt 
        pip install pytest pytest-cov
 
    - name: Run tests 
      run: |
        pytest tests/ --cov=./ --cov-report=xml 
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3 