name: CI Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest 
    timeout-minutes: 15 
    
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
 
    - name: Install TA-Lib system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential 
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz 
        tar -xzf ta-lib-0.4.0-src.tar.gz 
        cd ta-lib/
        ./configure --prefix=/usr
        make 
        sudo make install
        cd ..
        rm -rf ta-lib/ ta-lib-0.4.0-src.tar.gz 
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install wheel
        pip install numpy  # TA-Lib 需要先安装 numpy 
        pip install TA-Lib 
        pip install -r requirements.txt 
        pip install pytest pytest-cov
 
    - name: Run tests 
      run: |
        pytest tests/ --cov=./ --cov-report=xml 
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3 