name: CI Pipeline
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 
    
    steps:
    - uses: actions/checkout@v3
 
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          cmake
        
        # 安装 TA-Lib C 库 
        wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 
        tar -xzf ta-lib-0.4.0-src.tar.gz  
        cd ta-lib/
        ./configure --prefix=/usr 
        make -j$(nproc)
        sudo make install
        cd ..
        rm -rf ta-lib/ ta-lib-0.4.0-src.tar.gz 
 
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
 
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install numpy==1.24.3  # 必须指定兼容版本
        pip install Cython==3.0.0  # 明确指定 Cython 版本
        pip install TA-Lib==0.4.24 \
          --global-option=build_ext \
          --global-option="-L/usr/lib" \
          --global-option="-I/usr/include"
        pip install -r requirements.txt  
 
    - name: Verify installation
      run: |
        python -c "import talib; print(f'TA-Lib {talib.__version__} installed')"