name: QuantBot CI & Packaging
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build-and-package:
    runs-on: windows-latest 
    steps:
    - name: Configure Git 
      run: git config --global core.protectNTFS  false
 
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          *
          !configs/strategy_presets/
        fetch-depth: 1
 
    - name: Prepare environment 
      run: |
        mkdir -p configs/strategy_presets
        cp configs/strategy_presets/*.yaml configs/strategy_presets/ 2>nul || exit 0 
 
    - name: Install TA-Lib
      run: |
        choco install -y ta-lib --version=0.4.0.1
        echo "TA_LIBRARY_PATH=C:\Program Files\ta-lib\lib" >> $env:GITHUB_ENV 
        echo "TA_INCLUDE_PATH=C:\Program Files\ta-lib\include" >> $env:GITHUB_ENV
 
    - name: Setup Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.11' 
 
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy Cython TA-Lib pyinstaller 
        if exist requirements.txt  pip install -r requirements.txt  
 
    - name: Build executable 
      run: |
        # 完全安全的单行spec配置 
        echo 'a = Analysis(["main.py"],  datas=[("configs/strategy_presets/*.yaml", "configs/strategy_presets")])' > build.spec  
        echo 'exe = EXE(a.scripts,  name="QuantBot")' >> build.spec 
        pyinstaller --noconfirm --onefile build.spec 
 
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuantBot-Windows 
        path: dist/QuantBot.exe 