name: QuantBot CI Pipeline 
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
 
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          wget \
          python3-pip
 
    - name: Build TA-Lib (isolated)
      run: |
        mkdir -p ./libs/ta-lib 
        cd ./libs/ta-lib 
        wget https://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz 
        tar -xzf ta-lib-0.4.0-src.tar.gz  --strip-components=1 
        ./configure --prefix=$PWD/install --disable-ta-regtest 
        make -C src/ta_common
        make -C src/ta_func 
        make install 
 
    - name: Install Python dependencies 
      working-directory: ./QuantBot  # 关键修改：进入项目目录
      run: | 
        python -m pip install --upgrade pip
        pip install numpy Cython TA-Lib
        # 如果存在 requirements.txt  才安装
        [ -f requirements.txt  ] && pip install -r requirements.txt  || echo "No requirements.txt  found"
        
        # 设置环境变量
        echo "TA_LIBRARY_PATH=$(pwd)/libs/ta-lib/install/lib" >> $GITHUB_ENV 
        echo "TA_INCLUDE_PATH=$(pwd)/libs/ta-lib/install/include" >> $GITHUB_ENV
 
    - name: Verify installation
      working-directory: ./QuantBot 
      run: |
        # 验证 TA-Lib 
        python -c "import talib; print(f'TA-Lib {talib.__version__} loaded')"
        
        # 验证项目依赖 
        python -c "
        try:
            import numpy, cython
            print('Dependencies verified')
        except ImportError as e:
            print(f'Missing dependency: {e}')
            exit(1)
        "