name: TA-Lib Bulletproof Install 
 
on: [push, pull_request]
 
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: Install prebuilt TA-Lib 
      run: |
        # 使用Ubuntu官方源安装（100%可靠）
        sudo apt-get update 
        sudo apt-get install -y libta-lib-dev ta-lib 
        sudo ldconfig 
        
        # 验证安装 
        ls /usr/lib/libta_lib.so*  && ls /usr/include/ta-lib/
        
        # 安装Python封装（使用预编译wheel）
        pip install --only-binary=TA-Lib TA-Lib
        
        # 终极验证
        python -c "import talib; print(f'TA-Lib {talib.__version__} loaded'); \
                 from talib import RSI, MACD; print('Indicators working')"